---
- name: This playbook will demonstrate installation of apache server
  hosts: all
  tasks:
     - name: Install apache server
       apt: name=apache2 state=latest

     - name: Install git
       apt: name=git state=latest
